# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designe.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 516)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.inputlargura = QtWidgets.QLineEdit(self.centralwidget)
        self.inputlargura.setObjectName("inputlargura")
        self.gridLayout.addWidget(self.inputlargura, 5, 2, 1, 1)
        self.inputaltura = QtWidgets.QLineEdit(self.centralwidget)
        self.inputaltura.setObjectName("inputaltura")
        self.gridLayout.addWidget(self.inputaltura, 5, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 3, 1, 1)
        self.btnredimensionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnredimensionar.setObjectName("btnredimensionar")
        self.gridLayout.addWidget(self.btnredimensionar, 5, 5, 1, 1)
        self.btnsalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnsalvar.setObjectName("btnsalvar")
        self.gridLayout.addWidget(self.btnsalvar, 6, 5, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 686, 387))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelimg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelimg.setText("")
        self.labelimg.setObjectName("labelimg")
        self.gridLayout_2.addWidget(self.labelimg, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 6)
        self.btnEscolherarquivo = QtWidgets.QPushButton(self.centralwidget)
        self.btnEscolherarquivo.setObjectName("btnEscolherarquivo")
        self.gridLayout.addWidget(self.btnEscolherarquivo, 1, 5, 1, 1)
        self.inputAbrirarquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAbrirarquivo.setObjectName("inputAbrirarquivo")
        self.gridLayout.addWidget(self.inputAbrirarquivo, 1, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimensionar imagem"))
        self.label_2.setText(_translate("MainWindow", "Altura"))
        self.btnredimensionar.setText(_translate("MainWindow", "Redimensionar"))
        self.btnsalvar.setText(_translate("MainWindow", "Salvar"))
        self.btnEscolherarquivo.setText(_translate("MainWindow", "Escolher Arquivo"))
        self.label.setText(_translate("MainWindow", "Largura"))
